### PR TITLE
94 my courses content

### LINKED ISSUE #94: My Courses Page Content

### PR DESCRIPTION
**Pull request by dmols**
Ready to merge to dev. No issues. Note: I took out config.json out of the .gitignore because it might as well be updating as we go.

### CODE REVIEW

**Comment by mbrancato31** [comment]
there is a lot of commented code, clean it up before merge
on line 65 of MyCourses.js, shouldn't it be to login? since the token is wrong

**Review by collyntheshots — APPROVED** [review]
server/config.json needs to be left in the .gitignore file
there are a bunch of comments that need to get cleaned up but the code works just fine
also make sure to hide the "home button" on the login/registration page

**Review by mbrancato31 — APPROVED** [review]
looks good, a lot of commented code thought

**Comment by dmols** [comment]
Yeah I'll take one last look and delete the commented-out stuff I don't need anymore.

**Pull request merged**
