### PR TITLE
183 token expiration

### LINKED ISSUE #183: Token Expiration

### PR DESCRIPTION
**Pull request by mbrancato31**
- fix issue when token expires, now it takes you back to login
- when the token has 15 min left before expiring, verify token function will create a new token with 2 more hours and then it will be send back to the front end, in the front end it will replace the old token (this only works when the user is making calls to the server, if there is inactivity then the token will expire and will need to log in again)

### CODE REVIEW

**Comment by dmols** [comment]
So far it looks good, though it might be easier to test this after merging branch 181 into it (or to dev and then here) to make sure the module file upload issues don't come from the token change.

**Review by collyntheshots — CHANGES_REQUESTED** [review]
The user Id is lost in the new token see the following:

First Token:
UserIdLost


New Token:
UserIdLost2

**Review by collyntheshots — APPROVED** [review]
Everything should be good now after the fix

**Review by dmols — APPROVED** [review]
Changed the expiration time a few times to test the functionality and it works perfectly. Should be good to push.

**Pull request merged**
