### PR TITLE
122 update course info frontend

### LINKED ISSUE #122: "Update Course" Page Frontend Fix
- Figure out how to make the front end better for the courses page (when you click on a course). 
- Some of the padding and margins are off, investigate why.

### LINKED ISSUE #192: Category editing and Display
Currently after a course has been created the categories associated with it cannot be edited or seen without direct access to the database.

### PR DESCRIPTION
**Pull request by collyntheshots**
#122 
adds the course editing page allowing the creator to edit the course info with better UI

### CODE REVIEW

**Review by dmols — CHANGES_REQUESTED** [review]
Issues were on my end, submitting updated review.

**Review by dmols — CHANGES_REQUESTED** [review]
I'd make the edit course info box a little smaller so that it can fit in the screen. I think it'd look nicer if the scrollbar wasn't needed. Also the submit button on editCourse still pops up the "Successfully created course!" alert. Asides from that, everything looks great!

**Comment by collyntheshots** [comment]
"Successfully created course!" alert is changed to say something more appropriate

**Review by dmols — APPROVED** [review]
Looks good to me!

**Review by nlyra — APPROVED** [review]
Saw it working when I helped implement the edit categories functionality, and I also tested against null values as well additionally. Good on my end with that.

**Review by mbrancato31 — APPROVED** [review]

**Pull request merged**
